# Dockerfile para servir Angular build con Nginx
FROM node:20 AS build
WORKDIR /app
COPY . .
RUN npm install -g @angular/cli && npm install && ng build

FROM nginx:alpine
COPY --from=build /app/dist/frontendproject/browser /usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
